# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 016ddc1b987aa457fa454e35f054f5b1caf01a83c9434942ce15f5dd6c8d2b5284d51c33019106697295bc6e2f7ba18456f310aa85fa587ef083da2e3216a0aa

test:
  secret_key_base: bbe05eeec342e704424aed821201cbe72a3a86deb4eb31297147a36ca01b0b773362877e5d05a12bc396589866810468cc6f25b5dec9676e335c682bb5e6f328

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
